language: cpp

os:
  - linux

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - cppcheck
      - cmake
      - gcc-4.8

before_install:
  - sudo pip install cpplint

script:
  - cmake CMakeLists.txt && make
  - cppcheck --enable=all ./xmchord
  - cpplint xmchord/* --extensions=cc,h
  - cpplint xmchord/helper/* --extensions=cc,h
  - cpplint xmchord/model/* --extensions=cc,h